# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joseph Benedettini
email: Jabenedettini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Im a freelance Developer/Designer with a passion for the backend. Experienced
  in enterprise level web devlopment. Fluent in Javascript, HTML5, CSS3, and Apples Swift.
  Uses Angular 1-2, Node.js, Socket.io, JSON Web Tokens, Express, Sails, and much more.
baseurl: "/user" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_username: JBenedettini
twitter_username: NOTUSED
github_username:  JBenedettini

# Build settings
markdown: kramdown
